language: node_js
node_js:
   - 7

before_install:
  - sudo apt-get install wine

before_script:
   - npm install -g @angular/cli

script:
   - npm coverage
   - npm run codecov
   - npm run package:all

before_deploy:
  - scripts/pre_deploy.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: $TRAVIS_BUILD_DIR/pseudo*.zip
  skip_cleanup: true
  on:
    tags: true
