language: node_js
node_js:
   - 7

before_install:
  - sudo apt-get install wine

before_script:
   - npm install -g @angular/cli

script:
   - npm test
   - npm run package:all

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "/packages/smock-*/smock*"
  skip_cleanup: true
  on:
    tags: true
